# Generated by Django 2.1 on 2018-08-20 14:36

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('documento_numero', models.IntegerField()),
                ('pais_nacimiento', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('fecha_desde', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_hasta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('interes_diario', models.IntegerField()),
                ('unidad_interes', models.CharField(choices=[('E', 'pesos'), ('O', 'porcentaje')], max_length=1)),
                ('firmado', models.BooleanField(verbose_name='Firmado con puño y letra')),
                ('valor_dolar', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor de dólar al momento                                                     de la firma del contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('altura', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('codigopostal', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(choices=[('0', 'PB'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=1)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Direccion')),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='MontoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio alquiler')),
                ('fecha_desde', models.DateTimeField(verbose_name='Desde que fecha se                                                      comienza a cobrar este                                                      precio')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('costos_asociados', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Costo asociado a la                                                          observación')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_cobro', models.DateTimeField()),
                ('fecha_de_pago', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoLaboral',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('tenants.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Garante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('CBU', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Garante',
            },
            bases=('tenants.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('CBU', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Inquilino',
            },
            bases=('tenants.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrador', to=settings.AUTH_USER_MODEL, verbose_name='Administrador Local'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Lugar', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='pago',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Inquilino'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contacto_laboral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacto_laboral', to='tenants.ContactoLaboral'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='garantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Garante'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquilino', to='tenants.Inquilino'),
        ),
    ]
