# Generated by Django 2.1 on 2018-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_auto_20180820_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_desde',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_firma',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Firma'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='montocontrato',
            name='fecha_desde',
            field=models.DateField(verbose_name='Desde que fecha se                                                      comienza a cobrar este                                                      precio'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_de_cobro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_de_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
