# Generated by Django 2.1 on 2018-08-19 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='garante',
            options={'verbose_name': 'Garante'},
        ),
        migrations.AlterModelOptions(
            name='inquilino',
            options={'verbose_name': 'Inquilino'},
        ),
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name_plural': 'Propiedades'},
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='user',
            name='documento_numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 20, 0, 36, 106512)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pais_nacimiento',
            field=models.CharField(default='Argentina', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(default='DNI', max_length=100),
            preserve_default=False,
        ),
    ]
